### ISSUE TITLE
转换后图片ｉｄ与ｉｄ没有对上

### ISSUE THREAD

**Issue by cendelian** [zhengye1995/datafountain_siweituxin_autodriver_det#1]
使用提供的ｔｘｔ　２　ｊｓｏｎ函数转换后，ｉｄ与图片ｉｄ没有一一对应，请问这是正确的吗

**Comment by cendelian** [comment]
如下 image字段这里，
id 和file_name编号没有对上，
请问这是正确的吗？ 

 {
   "height": 720,
   "width": 1280,
   "id": 439,
   "file_name": "000447.jpg"
  },

**Comment by zhengye1995** [comment]
Absolutly no problem for detection, because some image do not has bbox in label, for example: 000038.jpg , so I just drop all images which do not have bbox in label.
