### ISSUE TITLE
faster_rcnn_r50_fpn.py 里面的num_class=81

### ISSUE THREAD

**Issue by cendelian** [zhengye1995/datafountain_siweituxin_autodriver_det#2]
请问为什么faster_rcnn_r50_fpn.py里面的num_class 还是设置为81呢

**Comment by zhengye1995** [comment]
This is a mistake, the num_class should set to the number of classes + 1(with background), thanks for your attention. 
And if your class number is smaller than 81, it is ok to train, but in test,  you should do not remain the class_id which bigger than class num of your dataset. So the best way is just change the 'num_class'.
